"""
run_manifest.py -- lightweight append-only run-tracking log.

Every pipeline stage (data generation, kinematic-estimate generation,
beta-fit, phase-shear fit) appends one JSON line to runs_manifest.jsonl at
the repo root via log_run(). This gives a single place to check what's
been generated/analyzed, under which tag, and with which params, across
both non_phase_shear/ and phase_shear/ -- without a database or any extra
infrastructure. Inspect it with `cat runs_manifest.jsonl | jq` or just
grep for a tag.
"""
import json
import time
from pathlib import Path


def log_run(repo_root, stage, label, **fields):
    """Append one line to <repo_root>/runs_manifest.jsonl.

    repo_root: path to the repo root (where runs_manifest.jsonl lives)
    stage: pipeline stage, e.g. 'generate_data', 'kinematic_estimates',
        'beta_fits', 'phase_shear_fit'
    label: the run/dataset tag -- by convention this matches the data/
        directory name (the --run_name passed to or auto-generated by
        generate_data.py), so every downstream stage's manifest entry can
        be traced back to the exact dataset it consumed.
    fields: any extra params worth recording (n_runs, n_shots, n_atoms,
        kappa, output path, ...)
    """
    entry = dict(timestamp=time.strftime('%Y-%m-%dT%H:%M:%S'),
                 stage=stage, label=label, **fields)
    manifest_path = Path(repo_root) / 'runs_manifest.jsonl'
    with open(manifest_path, 'a') as f:
        f.write(json.dumps(entry) + '\n')
    return manifest_path


def guard_label_reuse(sidecar_path, current, key_fields):
    """Refuse to silently overwrite output(s) tied to a --label whose
    identifying config (e.g. which data/ dataset dir, which --psmap_tag)
    has changed since the label was last used.

    Short, free-text --label args (e.g. '1e6') are convenient but are not
    otherwise tied to the actual dataset/PSMAP a script was run against --
    reusing one against a different dataset silently overwrites the
    previous JSON/figures with no error and no way to recover them (this is
    the downstream-analysis analogue of the data/ directory-name collision
    generate_data.py guards against; see _check_or_write_generation_config
    there for the sibling of this function).

    sidecar_path: a `<...>._label_config.json` path, conventionally placed
        next to the output(s) this call is meant to protect (e.g.
        alongside `results/kinematic_estimates_<label>_*.json`).
    current: dict of the config values for THIS invocation.
    key_fields: which keys of `current` must match a prior run under the
        same sidecar_path; only these are compared (and stored), so callers
        can pass unrelated bookkeeping through `current` without it
        spuriously tripping the guard.

    Aborts the process (sys.exit(1)) on a mismatch. Writes/updates the
    sidecar on a clean pass (first use, or a matching re-use).
    """
    import sys
    sidecar_path = Path(sidecar_path)
    to_store = {k: current[k] for k in key_fields}

    if sidecar_path.exists():
        with open(sidecar_path) as f:
            previous = json.load(f)
        mismatches = [k for k in key_fields if previous.get(k) != to_store[k]]
        if mismatches:
            print(f'\nABORTING: {sidecar_path}\nrecords a different config than this invocation is '
                  f'about to use for the same label. Mismatched key(s): {", ".join(mismatches)}.\n'
                  f'  previous : { {k: previous.get(k) for k in mismatches} }\n'
                  f'  current  : { {k: to_store[k] for k in mismatches} }\n'
                  f'Continuing would silently overwrite output(s) generated under the previous '
                  f'config with no way to recover them. Use a different --label for this config, '
                  f'or delete {sidecar_path.name} if you are deliberately regenerating from '
                  f'scratch under the same label.', file=sys.stderr)
            sys.exit(1)
        return

    sidecar_path.parent.mkdir(parents=True, exist_ok=True)
    with open(sidecar_path, 'w') as f:
        json.dump(to_store, f, indent=2)
