"""
run_manifest.py -- lightweight append-only run-tracking log.

Every pipeline stage (data generation, kinematic-estimate generation,
beta-fit, phase-shear fit) appends one JSON line to runs_manifest.jsonl at
the repo root via log_run(). This gives a single place to check what's
been generated/analyzed, under which tag, and with which params, across
both non_phase_shear/ and phase_shear/ -- without a database or any extra
infrastructure. Inspect it with `cat runs_manifest.jsonl | jq` or just
grep for a tag.
"""
import json
import time
from pathlib import Path


def log_run(repo_root, stage, label, **fields):
    """Append one line to <repo_root>/runs_manifest.jsonl.

    repo_root: path to the repo root (where runs_manifest.jsonl lives)
    stage: pipeline stage, e.g. 'generate_data', 'kinematic_estimates',
        'beta_fits', 'phase_shear_fit'
    label: the run/dataset tag -- by convention this matches the data/
        directory name (the --run_name passed to or auto-generated by
        generate_data.py), so every downstream stage's manifest entry can
        be traced back to the exact dataset it consumed.
    fields: any extra params worth recording (n_runs, n_shots, n_atoms,
        kappa, output path, ...)
    """
    entry = dict(timestamp=time.strftime('%Y-%m-%dT%H:%M:%S'),
                 stage=stage, label=label, **fields)
    manifest_path = Path(repo_root) / 'runs_manifest.jsonl'
    with open(manifest_path, 'a') as f:
        f.write(json.dumps(entry) + '\n')
    return manifest_path
