#!/usr/bin/env python
"""
fit_image_mle_distributions.py — Position-resolved image MLE over repeated runs.

Fits the 2-parameter sinusoidal differential-phase signal model using the
full position-resolved Poisson likelihood for MAGIS-100 gradiometer image data.

Unlike the count-only fitter (fit_mle_distributions.py), this pipeline uses
the 2D atom images to exploit spatial information from the PSMAP wavefront
structure.  The key advantages are:

  • Phase sensitivity: atoms at different transverse positions accumulate
    different differential phases (from the PSMAP wavefront).  Grouping them
    by position extracts this extra information.
  • No phi0 parameter: the intrinsic AI-to-AI phase offset is encoded in the
    PSMAP Δφ(q0) difference between Z0 and Z100.  Only (As, Ac) are free.
  • Fewer optimizer degrees of freedom: 2 parameters instead of 7.

Mathematical model
------------------
For each shot i, AI z ∈ {Z0, Z100}, state s ∈ {g, e}, and pixel b:

    n_izsb ~ Poisson(λ_izsb(Φ_iz))

    λ_izsb(Φ) = Λ_iz · [A_izsb + Cc_izsb·cos(Φ) + Cs_izsb·sin(Φ)]

    Φ_z0  = φ_i                          (common laser phase, marginalised)
    Φ_z100 = φ_i + δφ_i                  (signal enters Z100 only)
    δφ_i   = As·sin(2π·f·t_i) + Ac·cos(2π·f·t_i)

The pixel statistics (A, Cc, Cs) are pre-computed ONCE per run from the PSMAP
and the per-shot cloud shape (COM estimated from sum image, spreads from args).

Directory layout
----------------
Expects datasets generated by generate_data.py with layout:

    <run_name>/run_000/Z0/data_IMG.h5
    <run_name>/run_000/Z100/data_IMG.h5
    <run_name>/run_001/Z0/data_IMG.h5
    ...

Output
------
A pickle file containing a DataFrame with one row per fitted run:

    run_idx, As, Ac, amp, phase, logL, logL_null, delta_logL, f, ntheta,
    converged, optimizer_status, optimizer_message, optimizer_nit,
    optimizer_nfev, optimizer_objective, n_coarse_starts,
    fine_start_As, fine_start_Ac, fine_start_objectives

Resuming
--------
Use --resume to continue from a previously checkpointed output file.
Completed runs are skipped; new rows are appended.

Usage
-----
    python fit_image_mle_distributions.py <run_name> --frequency 0.3

    # Override cloud spread parameters (default: read from dataset attrs)
    python fit_image_mle_distributions.py <run_name> \\
        --sigma-vx 3.09e-4 --sigma-x 100e-6

    # Downsample to 64 bins for more spatial resolution (slower)
    python fit_image_mle_distributions.py <run_name> --bins 64

    # Resume interrupted job
    python fit_image_mle_distributions.py <run_name> --resume

    # Fast mode for quick checks
    python fit_image_mle_distributions.py <run_name> --fast
"""

import argparse
from dataclasses import asdict
import logging
import os
from pathlib import Path
import re
import sys
import time

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "helpers"))

from helpers import ImageShotDataset            # noqa: E402
from image_fitting import fit_image_mle, ImageFitResult   # noqa: E402
from image_likelihood import ImageLikelihoodEvaluator     # noqa: E402

# Resolve aispy path
_AISPY_ROOT = REPO_ROOT.parents[1] / "local" / "aispy"
if str(_AISPY_ROOT) not in sys.path:
    sys.path.insert(0, str(_AISPY_ROOT))
from aispy.psmap import load_psmap   # noqa: E402

# ── Default paths ──────────────────────────────────────────────────────────────
DEFAULT_PSMAP_Z0   = REPO_ROOT / "output-files" / "PSGRID4D_CONFOCAL_Z0.h5"
DEFAULT_PSMAP_Z100 = REPO_ROOT / "output-files" / "PSGRID4D_CONFOCAL_Z100.h5"
DEFAULT_RUN_NAME   = (
    REPO_ROOT
    / "data"
    / "R80_N50_A1000000_muXStd10.0um_muVxStd10.0um_"
      "sigX100um_sigVx309um_sigXStd10.0um_sigVxStd10.0um_phi0random_sig_A0.100_f0.3000"
)

# ── Result columns (matches the existing result format where applicable) ───────
RESULT_COLUMNS = [
    "run_idx",
    "As", "Ac", "amp", "phase",
    "logL", "logL_null", "delta_logL",
    "f", "ntheta", "converged",
    "optimizer_status", "optimizer_message",
    "optimizer_nit", "optimizer_nfev", "optimizer_objective",
    "n_coarse_starts", "fine_start_As", "fine_start_Ac",
    "fine_start_objectives",
    # Provenance
    "bins", "hermite_order", "sigma_vx", "sigma_x",
    "run_name",
]


# ── Helpers ────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "run_name", nargs="?", type=Path, default=DEFAULT_RUN_NAME,
        help="Dataset directory containing run_### subdirectories.",
    )
    p.add_argument(
        "--frequency", "-f", type=float, default=0.3,
        help="Signal frequency [cycles per shot index]. (default: %(default)s)",
    )
    p.add_argument(
        "--run-start", type=int, default=0,
        help="First run index to fit.  Ignored if --resume finds more rows.",
    )
    p.add_argument(
        "--run-stop", type=int, default=None,
        help="Exclusive stop run index.  Defaults to total run count.",
    )
    p.add_argument(
        "--output", type=Path, default=None,
        help="Output pickle path. Defaults to results/<run_name>_image_mle.pkl.",
    )
    p.add_argument(
        "--log-file", type=Path, default=None,
        help="Log path. Defaults to logs/fit_image_<run_name>.log.",
    )
    p.add_argument(
        "--resume", action="store_true",
        help="Skip runs already saved in the output pickle.",
    )
    p.add_argument(
        "--overwrite", action="store_true",
        help="Replace an existing output instead of refusing to start.",
    )
    p.add_argument(
        "--psmap-z0", type=Path, default=DEFAULT_PSMAP_Z0,
        help="Z0 PSMAP HDF5 file. (default: %(default)s)",
    )
    p.add_argument(
        "--psmap-z100", type=Path, default=DEFAULT_PSMAP_Z100,
        help="Z100 PSMAP HDF5 file. (default: %(default)s)",
    )
    p.add_argument(
        "--bins", type=int, default=32,
        help=(
            "Downsampled image resolution per axis. "
            "Total pixels = bins². (default: %(default)s)"
        ),
    )
    p.add_argument(
        "--hermite-order", type=int, default=5,
        help=(
            "Gauss-Hermite quadrature order for the velocity integral per pixel. "
            "hermite_order² nodes per pixel. (default: %(default)s)"
        ),
    )
    p.add_argument(
        "--ntheta", type=int, default=None,
        help="Phase quadrature grid size. Defaults to adaptive (≥ 2·√N_detected).",
    )
    p.add_argument(
        "--sigma-vx", type=float, default=3.09e-4,
        help=(
            "Known initial velocity spread σ_vx0 [m/s]. "
            "Used to compute the conditional velocity distribution at each pixel. "
            "(default: %(default)g — matches CONFOCAL generation default)"
        ),
    )
    p.add_argument(
        "--sigma-x", type=float, default=None,
        help=(
            "Known initial position spread σ_x0 [m]. "
            "If omitted, estimated from the image half_range attribute."
        ),
    )
    p.add_argument(
        "--as-starts", nargs="+", type=float,
        default=[0.0, 0.03, 0.07, 0.12, 0.20],
        help=(
            "As starting values for Stage-1 coarse optimisation. "
            "Each is tried with Ac=0. (default: %(default)s)"
        ),
    )
    p.add_argument(
        "--fast", action="store_true",
        help=(
            "Speed-optimised fitting mode: fewer starts, looser tolerances. "
            "Accuracy loss is typically < 0.5%% on amp/phase."
        ),
    )
    p.add_argument(
        "--cpu", action="store_true",
        help="Force NumPy/CPU evaluation (no CuPy).",
    )
    p.add_argument(
        "--verbose", "-v", action="store_true",
        help="Include DEBUG details in the log.",
    )
    return p.parse_args()


def infer_run_count(run_name: Path) -> int:
    """Infer total run count from the R<N>_ prefix or the directory contents."""
    match = re.match(r"R(\d+)(?:_|$)", run_name.name)
    if match:
        return int(match.group(1))
    run_dirs = sorted(run_name.glob("run_[0-9][0-9][0-9]"))
    if not run_dirs:
        raise ValueError(
            f"Cannot infer run count from {run_name.name!r}. "
            "No run_### directories found."
        )
    return max(int(d.name.removeprefix("run_")) for d in run_dirs) + 1


def configure_logging(log_file: Path, verbose: bool) -> None:
    log_file.parent.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(log_file, mode="a"),
        ],
    )


def save_checkpoint(rows: list, output: Path) -> None:
    """Atomic write: save rows to a .tmp file then rename to output."""
    output.parent.mkdir(parents=True, exist_ok=True)
    df  = pd.DataFrame(rows, columns=RESULT_COLUMNS)
    tmp = output.with_suffix(output.suffix + ".tmp")
    df.to_pickle(tmp)
    os.replace(tmp, output)
    logging.debug("Checkpoint saved: %s (%d rows)", output, len(rows))


def result_to_row(result: ImageFitResult, run_idx: int,
                  bins: int, hermite_order: int,
                  sigma_vx: float, sigma_x: float | None,
                  run_name: str) -> dict:
    """Convert an ImageFitResult to a flat dict matching RESULT_COLUMNS."""
    d = asdict(result)
    d["run_idx"]      = run_idx
    d["bins"]         = bins
    d["hermite_order"] = hermite_order
    d["sigma_vx"]     = sigma_vx
    d["sigma_x"]      = sigma_x
    d["run_name"]     = run_name
    return {col: d.get(col) for col in RESULT_COLUMNS}


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    args     = parse_args()
    run_name = args.run_name.expanduser().resolve()

    # ── output paths ──────────────────────────────────────────────────────────
    if args.output is None:
        output = REPO_ROOT / "results" / f"{run_name.name}_image_mle.pkl"
    else:
        output = args.output.expanduser().resolve()

    if args.log_file is None:
        log_file = REPO_ROOT / "logs" / f"fit_image_{run_name.name}.log"
    else:
        log_file = args.log_file.expanduser().resolve()

    configure_logging(log_file, args.verbose)

    # ── guards ────────────────────────────────────────────────────────────────
    if args.resume and args.overwrite:
        raise ValueError("--resume and --overwrite cannot be used together.")
    if output.exists() and not args.resume and not args.overwrite:
        raise FileExistsError(
            f"Output already exists: {output}\n"
            "Use --resume to append or --overwrite to replace."
        )
    if not run_name.is_dir():
        raise FileNotFoundError(f"Dataset directory not found: {run_name}")
    if not args.psmap_z0.is_file():
        raise FileNotFoundError(f"Z0 PSMAP not found: {args.psmap_z0}")
    if not args.psmap_z100.is_file():
        raise FileNotFoundError(f"Z100 PSMAP not found: {args.psmap_z100}")

    # ── run range ─────────────────────────────────────────────────────────────
    n_runs   = infer_run_count(run_name)
    run_stop = n_runs if args.run_stop is None else args.run_stop
    rows     = []
    start    = args.run_start

    if args.resume and output.exists():
        existing = pd.read_pickle(output)
        rows     = existing.reindex(columns=RESULT_COLUMNS).to_dict("records")
        start    = max(start, len(rows))
        logging.info("Resuming from row %d (%d already saved).", start, len(rows))

    # ── startup logging ───────────────────────────────────────────────────────
    logging.info("=" * 70)
    logging.info("Position-resolved image MLE fitting")
    logging.info("Dataset   : %s", run_name)
    logging.info("Runs      : %d – %d  (%d total)", start, run_stop, run_stop - start)
    logging.info("Frequency : %.4f cycles/shot", args.frequency)
    logging.info("Bins      : %d×%d = %d pixels", args.bins, args.bins, args.bins**2)
    logging.info("GH order  : %d  (%d nodes/pixel)", args.hermite_order, args.hermite_order**2)
    logging.info("ntheta    : %s (adaptive)", args.ntheta or "adaptive")
    logging.info("sigma_vx  : %.3g m/s", args.sigma_vx)
    logging.info("sigma_x   : %s m", f"{args.sigma_x:.3g}" if args.sigma_x else "estimated from dataset")
    logging.info("As starts : %s", args.as_starts)
    logging.info("Fast mode : %s", args.fast)
    logging.info("Backend   : %s", "numpy (CPU)" if args.cpu else "cupy (GPU) if available")
    logging.info("Output    : %s", output)
    logging.info("=" * 70)

    # ── load PSMAPs once ──────────────────────────────────────────────────────
    logging.info("Loading PSMAPs…")
    t0 = time.perf_counter()
    psmap_z0  = load_psmap(str(args.psmap_z0))
    psmap_z100 = load_psmap(str(args.psmap_z100))
    logging.info("PSMAPs loaded in %.1fs.", time.perf_counter() - t0)

    # ── main loop ─────────────────────────────────────────────────────────────
    job_start  = time.perf_counter()
    run_times  = []

    for run_idx in range(start, run_stop):
        local_i = run_idx - start

        # ETA based on completed runs
        eta_str = ""
        if run_times:
            avg = float(np.mean(run_times))
            remaining = (run_stop - run_idx) * avg
            m, s = divmod(int(remaining), 60)
            eta_str = f"  ETA {m}m{s:02d}s"

        logging.info(
            "── run %03d  (%d/%d)%s",
            run_idx, local_i + 1, run_stop - start, eta_str,
        )
        t_run = time.perf_counter()

        # Locate data files
        run_dir = run_name / f"run_{run_idx:03d}"
        path_z0  = run_dir / "Z0"  / "data_IMG.h5"
        path_z100 = run_dir / "Z100" / "data_IMG.h5"

        if not path_z0.is_file():
            logging.error("Missing Z0 data: %s  — skipping run %03d", path_z0, run_idx)
            continue
        if not path_z100.is_file():
            logging.error("Missing Z100 data: %s  — skipping run %03d", path_z100, run_idx)
            continue

        ds_z0  = ImageShotDataset(str(path_z0))
        ds_z100 = ImageShotDataset(str(path_z100))

        # Construct evaluator (pre-computation happens here)
        ev = ImageLikelihoodEvaluator(
            ds_z0, ds_z100,
            psmap_z0, psmap_z100,
            sigma_vx=args.sigma_vx,
            sigma_x=args.sigma_x,
            bins=args.bins,
            hermite_order=args.hermite_order,
            ntheta=args.ntheta,
            f=args.frequency,
            use_gpu=not args.cpu,
            verbose=True,
        )
        logging.info("%s", ev)

        # Fit
        logging.info("Fitting (As, Ac)…")
        t_fit = time.perf_counter()
        result = fit_image_mle(
            ev,
            as_starts=tuple(args.as_starts),
            fast=args.fast,
        )
        t_elapsed_fit = time.perf_counter() - t_fit

        logging.info(
            "  As=%.4f  Ac=%.4f  amp=%.4f rad  phase=%.4f rad",
            result.As, result.Ac, result.amp, result.phase,
        )
        logging.info(
            "  logL=%.2f  logL_null=%.2f  ΔlogL=%.2f",
            result.logL, result.logL_null, result.delta_logL,
        )
        logging.info(
            "  converged=%s  nit=%d  nfev=%d  fit_time=%.1fs",
            result.converged, result.optimizer_nit,
            result.optimizer_nfev, t_elapsed_fit,
        )

        # Record and checkpoint
        row = result_to_row(
            result, run_idx,
            bins=args.bins,
            hermite_order=args.hermite_order,
            sigma_vx=args.sigma_vx,
            sigma_x=args.sigma_x,
            run_name=str(run_name.name),
        )
        rows.append(row)
        save_checkpoint(rows, output)

        elapsed_run = time.perf_counter() - t_run
        run_times.append(elapsed_run)
        logging.info("  run %03d done in %.0fs\n", run_idx, elapsed_run)

    # ── summary ───────────────────────────────────────────────────────────────
    total = time.perf_counter() - job_start
    m, s  = divmod(int(total), 60)
    logging.info(
        "All %d run(s) done. Total wall time: %dm%02ds  (%.0fs/run).",
        run_stop - start,
        m, s,
        total / max(run_stop - start, 1),
    )
    logging.info("Results saved to: %s", output)

    # Print a brief summary table
    if rows:
        df = pd.DataFrame(rows, columns=RESULT_COLUMNS)
        print("\nSummary")
        print("-------")
        print(f"  runs        : {len(df)}")
        print(f"  amp  mean   : {df['amp'].mean():.4f} rad")
        print(f"  amp  std    : {df['amp'].std():.4f} rad")
        print(f"  phase mean  : {df['phase'].mean():.4f} rad")
        print(f"  phase std   : {df['phase'].std():.4f} rad")
        print(f"  ΔlogL mean  : {df['delta_logL'].mean():.1f}")
        print(f"  converged   : {df['converged'].sum()}/{len(df)}")
        print(f"  output      : {output}")


if __name__ == "__main__":
    main()
